service: encodrive-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    USERS_TABLE: EncodriveUsers
    FILES_TABLE: EncodriveFiles
    S3_BUCKET: encodrive-files
    API_KEY_SECRET: ${env:API_KEY_SECRET}
    GMAIL_USER: ${env:GMAIL_USER}
    GMAIL_PASS: ${env:GMAIL_PASS}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:ap-south-1:*:table/EncodriveUsers
        - arn:aws:dynamodb:ap-south-1:*:table/EncodriveFiles

functions:
  api:
    handler: src/handler.handler
    timeout: 20
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline
